name: Update PR Reviewers

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write
  contents: read  

jobs:
  update-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Remove all reviewers and add specific groups
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Small delay helps avoid race with CODEOWNERS auto-requests
            await new Promise(r => setTimeout(r, 3000));

            // Team slugs
            const desiredTeams = ['peer-code-reviewers', 'senior-code-reviewers']; 
            let reviewers = [];
            let data = {};

            try {
              // Fetch the PR and user details
              data = await github.rest.pulls.listReviews({
                owner, repo, pull_number: prNumber
              });

              // Users who have reviewed or been requested
              reviewers = data.filter(r => r.user).map(r => r.user.login);

              core.info(`Found requested reviewers: ${reviewers.join(', ') || '(none)'}`);
            } catch (error) {
              console.error("Error fetching PR details:", error.message);
            }
            
            // Optional: remove existing reviewers (GitHub may auto-reassign CODEOWNERS)
            try {
              if (reviewers.length || teams.length) {
                await github.rest.pulls.removeRequestedReviewers({
                  owner, repo, pull_number: prNumber,
                  reviewers: reviewers,
                  team_reviewers: teams
                });

                core.info('Removed all currently requested reviewers.');
              } 
            } catch (error) {
              console.log("No requested reviewers to remove or error occurred:", error.message);
            }

            // Adds teams to PR
            try {
              await github.rest.pulls.requestReviewers({
                owner, repo, pull_number: prNumber,
                team_reviewers: desiredTeams
              });

              core.info(`Requested review from teams: ${desiredTeams.join(', ')}`);
            } catch (error) {
              core.info('All desired teams already requested or error occured:', error.message);
            }